//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pundit.WinForms.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pundit.WinForms.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution failed with conflicts!.
        /// </summary>
        internal static string Resolve_MessageConflicts {
            get {
                return ResourceManager.GetString("Resolve_MessageConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading manifest....
        /// </summary>
        internal static string Resolve_ReadingManifest {
            get {
                return ResourceManager.GetString("Resolve_ReadingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading repositories....
        /// </summary>
        internal static string Resolve_ReadingRepositories {
            get {
                return ResourceManager.GetString("Resolve_ReadingRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hating MAPI....
        /// </summary>
        internal static string Resolve_Resolving {
            get {
                return ResourceManager.GetString("Resolve_Resolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all done.
        /// </summary>
        internal static string Resolve_Success {
            get {
                return ResourceManager.GetString("Resolve_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled by user!.
        /// </summary>
        internal static string Resolve_Terminated {
            get {
                return ResourceManager.GetString("Resolve_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terminating resolution....
        /// </summary>
        internal static string Resolve_Terminating {
            get {
                return ResourceManager.GetString("Resolve_Terminating", resourceCulture);
            }
        }
    }
}
