!define PRODUCT_NAME "Pundit"
!define PRODUCT_SHORT_NAME "Pundit"
!define PRODUCT_DIR_NAME "Pundit"
!define PRODUCT_VERSION "1.1.0.2"
!define PRODUCT_PUBLISHER "Ivan Gavryliuk"
!define PRODUCT_WEB_SITE "http://pundit.codeplex.com"
!define OUTFILE "..\..\pundit-setup.exe"