//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pundit.Vsix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pundit.Vsix.Resources.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pundit.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Dependency Management System.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio has no idea why the window cannot be created.
        /// </summary>
        internal static string CantCreateToolWindow {
            get {
                return ResourceManager.GetString("CantCreateToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&gt; .
        /// </summary>
        internal static string Console_Prompt {
            get {
                return ResourceManager.GetString("Console_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2010 status bar not found.
        /// </summary>
        internal static string Ex_CantFindStatusBar {
            get {
                return ResourceManager.GetString("Ex_CantFindStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution has a Pundit manifest from a previous version which is not fully compatible with Visual Studio IntelliSense. Would you like to upgrade it now to a new format (old manifest will be backed up into the original folder)?.
        /// </summary>
        internal static string Manifest_NeedsUpgrade {
            get {
                return ResourceManager.GetString("Manifest_NeedsUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest upgrade failed: {0}.
        /// </summary>
        internal static string Manifest_UpgradeFail {
            get {
                return ResourceManager.GetString("Manifest_UpgradeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest successfully upgraded. Have a nice weekend!.
        /// </summary>
        internal static string Manifest_UpgradeOk {
            get {
                return ResourceManager.GetString("Manifest_UpgradeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing manifest located at {0} is not using Pundit XSD namespace. As a result, you will not be able to use Visual Studio Intellisense. Would you like to automatically fix this problem?.
        /// </summary>
        internal static string ManifestNotUsingNamespace {
            get {
                return ResourceManager.GetString("ManifestNotUsingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution has no Pundit manifest. Would you like to create a new one at &apos;{0}&apos;?.
        /// </summary>
        internal static string OpenXmlManifest_DoesntExist {
            get {
                return ResourceManager.GetString("OpenXmlManifest_DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pundit Console.
        /// </summary>
        internal static string PunditConsoleWindowTitle {
            get {
                return ResourceManager.GetString("PunditConsoleWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access solution properties. Is any solution open at at all at the moment?.
        /// </summary>
        internal static string SolutionNotAccessible {
            get {
                return ResourceManager.GetString("SolutionNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upgrade XSD schema. Make sure you have enough permissions to access the target folder..
        /// </summary>
        internal static string Xsd_CantUpgrade {
            get {
                return ResourceManager.GetString("Xsd_CantUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to upgrade XSD manifest at &apos;{0}&apos;....
        /// </summary>
        internal static string Xsd_Start {
            get {
                return ResourceManager.GetString("Xsd_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD schema upgraded.
        /// </summary>
        internal static string Xsd_Upgraded {
            get {
                return ResourceManager.GetString("Xsd_Upgraded", resourceCulture);
            }
        }
    }
}
